server:
  port: 8030
  address: 192.168.100.37
spring:
  datasource:
    url: jdbc:mysql://192.168.18.128:3306/htqyjsw?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.37:8761/eureka/

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.htqyjsw1.entity