server:
  port: 8030
  address: localhost
spring:
  datasource:
    url: jdbc:mysql://192.168.18.128:3306/htqyjsw?serverTimezone=UTC&useSSL=true
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.htqyjsw1.entity