server:
  port: 8086

security:
  oauth2:
    client:
      client-id: ben1
      client-secret: 123456
      user-authorization-uri: http://localhost:8080/test/oauth/authorize
      access-token-uri: http://localhost:8080/test/oauth/token
      registered-redirect-uri:
    resource:
      jwt:
        key-uri: http://localhost:8080/test/oauth/token_key
