server:
  port: 8030

spring:
  datasource:
    url: jdbc:mysql://192.168.18.128:3306/htqyjsw?serverTimezone=UTC&useSSL=true
    username: root
    password: 123456

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: mapper/*.xml