server:
  port: 8762
spring:
  application:
    name: config-server
  profiles:
    active: native    #native 代表本地
  cloud:
    config:
      server:
        native:
          search-locations: classpath:shared

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


