package com.htqyjsw1.searchpage.domain;


import java.util.Date;

public class NewWordDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_newentity.con_time
     *
     * @mbg.generated Fri Nov 29 14:57:26 CST 2019
     */
    private Date conTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_newentity.new_entity
     *
     * @mbg.generated Fri Nov 29 14:57:26 CST 2019
     */
    private String newEntity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_newentity.con_time
     *
     * @return the value of t_newentity.con_time
     * @mbg.generated Fri Nov 29 14:57:26 CST 2019
     */
    public Date getConTime() {
        return conTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_newentity.con_time
     *
     * @param conTime the value for t_newentity.con_time
     * @mbg.generated Fri Nov 29 14:57:26 CST 2019
     */
    public void setConTime(Date conTime) {
        this.conTime = conTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_newentity.new_entity
     *
     * @return the value of t_newentity.new_entity
     * @mbg.generated Fri Nov 29 14:57:26 CST 2019
     */
    public String getNewEntity() {
        return newEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_newentity.new_entity
     *
     * @param newEntity the value for t_newentity.new_entity
     * @mbg.generated Fri Nov 29 14:57:26 CST 2019
     */
    public void setNewEntity(String newEntity) {
        this.newEntity = newEntity;
    }
}